export const SET_ROOTROUTE = "SET_ROOTROUTE";
export const GO_TO_URL = "GO_TO_URL";
export const OBVERSE_WINDOW_SIZE_START = "OBVERSE_WINDOW_SIZE_START";
export const OBVERSE_WINDOW_SIZE_END = "OBVERSE_WINDOW_SIZE_END";
