const FRAME_UPDATE_REFRESH = "FRAME_UPDATE_REFRESH";
const FRAME_UPDATE_NOREFRESH = "FRAME_UPDATE_NOREFRESH";
const FRAME_REFRESH = "FRAME_REFRESH";
const FRAME_SNACKBAR_SHOW = "FRAME_SNACKBAR_SHOW";
const FRAME_SNACKBAR_CLOSE = "FRAME_SNACKBAR_CLOSE";
const FRAME_SNACKBAR_CANCEL = "FRAME_SNACKBAR_CANCEL";
const FRAME_SNACKBAR_ADD = "FRAME_SNACKBAR_ADD";
const FRAME_LOAD_MENUDATA = "FRAME_LOAD_MENUDATA";

const FRAME_LEFTNAVBAR = "FRAME_LEFTNAVBAR";

const FRAME_USER_TOKEN_ERROR = "FRAME_USER_TOKEN_ERROR";
const FRAME_USER_LOGOUT = "FRAME_USER_LOGOUT";
const FRAME_USER_LOGIN = "FRAME_USER_LOGIN";

const FRAME_PAGE_JUMP = "FRAME_PAGE_JUMP";
const FRAME_PAGE_BACKWARD = "FRAME_PAGE_BACKWARD";
const FRAME_SET_ROOTROUTE = "FRAME_SET_ROOTROUTE";
const FRAME_ROUTE_HOTREPLACE = "FRAME_ROUTE_HOTREPLACE";
const FRAME_ROUTE_REFRESH = "FRAME_ROUTE_REFRESH";

const FRAME_LOAD_PAGE = "FRAME_LOAD_PAGE";
const FRAME_NAV_DIALOG = "FRAME_NAV_DIALOG";
const FRAME_HISTORY_REGISTER = "FRAME_HISTORY_REGISTER";

const FRAME_PAGE_REFRESH = "FRAME_PAGE_REFRESH";
const FRAME_REGISTER_PAGECONTAINER = "FRAME_REGISTER_PAGECONTAINER";
const FRAME_WINDOW_RESIZE = "FRAME_WINDOW_RESIZE";

const FRAME_SCROLL_TO_TOP = "FRAME_SCROLL_TO_TOP";
const FRAME_LOAD_USERAPPDATA = "FRAME_LOAD_USERAPPDATA";

const PAGE_UPDATE_REFRESH = "PAGE_UPDATE_REFRESH";
const PAGE_UPDATE_NOREFRESH = "PAGE_UPDATE_NOREFRESH";
const PAGE_REFRESH = "PAGE_REFRESH";
const PAGE_SET_STATE = "PAGE_SET_STATE";
const PAGE_INIT_CUSTOM_REDUX = "PAGE_INIT_CUSTOM_REDUX";
const PAGE_DSTY_CUSTOM_REDUX = "PAGE_DSTY_CUSTOM_REDUX";
const PAGE_APPL_CUSTOM_REDUX = "PAGE_APPL_CUSTOM_REDUX";

const FRAME_CHANGE_THEME = "FRAME_CHANGE_THEME";
const PAGE_LOAD_START = "PAGE_LOAD_START";
const PAGE_LOAD_END = "PAGE_LOAD_END";
const PAGE_SET_CUR_MENU_DATA = "PAGE_SET_CUR_MENU_DATA";
const PAGE_APPLY_REDUX = "PAGE_APPLY_REDUX";

export {
  FRAME_UPDATE_REFRESH,
  FRAME_UPDATE_NOREFRESH,
  FRAME_REFRESH,
  FRAME_SNACKBAR_SHOW,
  FRAME_SNACKBAR_CLOSE,
  FRAME_SNACKBAR_CANCEL,
  FRAME_SNACKBAR_ADD,
  FRAME_REGISTER_PAGECONTAINER,
  FRAME_LEFTNAVBAR,
  FRAME_LOAD_MENUDATA,
  FRAME_USER_TOKEN_ERROR,
  FRAME_USER_LOGIN,
  FRAME_USER_LOGOUT,
  FRAME_HISTORY_REGISTER,
  FRAME_LOAD_PAGE,
  FRAME_PAGE_JUMP,
  FRAME_PAGE_BACKWARD,
  FRAME_NAV_DIALOG,
  FRAME_PAGE_REFRESH,
  FRAME_WINDOW_RESIZE,
  FRAME_SCROLL_TO_TOP,
  FRAME_CHANGE_THEME,
  FRAME_LOAD_USERAPPDATA,
  PAGE_UPDATE_REFRESH,
  PAGE_UPDATE_NOREFRESH,
  PAGE_REFRESH,
  PAGE_LOAD_START,
  PAGE_LOAD_END,
  PAGE_SET_STATE,
  PAGE_INIT_CUSTOM_REDUX,
  PAGE_DSTY_CUSTOM_REDUX,
  PAGE_APPL_CUSTOM_REDUX,
  PAGE_SET_CUR_MENU_DATA,
  PAGE_APPLY_REDUX,
  FRAME_SET_ROOTROUTE,
  FRAME_ROUTE_HOTREPLACE,
  FRAME_ROUTE_REFRESH
};
