export const FRAME_UPDATE_REFRESH = "FRAME_UPDATE_REFRESH";
export const FRAME_UPDATE_NOREFRESH = "FRAME_UPDATE_NOREFRESH";
export const FRAME_REFRESH = "FRAME_REFRESH";
export const FRAME_SNACKBAR_SHOW = "FRAME_SNACKBAR_SHOW";
export const FRAME_SNACKBAR_CLOSE = "FRAME_SNACKBAR_CLOSE";
export const FRAME_SNACKBAR_CANCEL = "FRAME_SNACKBAR_CANCEL";
export const FRAME_SNACKBAR_ADD = "FRAME_SNACKBAR_ADD";
export const FRAME_LOAD_MENUDATA = "FRAME_LOAD_MENUDATA";

export const FRAME_LEFTNAVBAR = "FRAME_LEFTNAVBAR";

export const FRAME_USER_TOKEN_ERROR = "FRAME_USER_TOKEN_ERROR";
export const FRAME_USER_LOGOUT = "FRAME_USER_LOGOUT";
export const FRAME_USER_LOGIN = "FRAME_USER_LOGIN";

export const FRAME_PAGE_JUMP = "FRAME_PAGE_JUMP";
export const FRAME_PAGE_BACKWARD = "FRAME_PAGE_BACKWARD";
export const FRAME_SET_ROOTROUTE = "FRAME_SET_ROOTROUTE";
export const FRAME_ROUTE_HOTREPLACE = "FRAME_ROUTE_HOTREPLACE";
export const FRAME_ROUTE_REFRESH = "FRAME_ROUTE_REFRESH";

export const FRAME_LOAD_PAGE = "FRAME_LOAD_PAGE";
export const FRAME_NAV_DIALOG = "FRAME_NAV_DIALOG";

export const FRAME_PAGE_REFRESH = "FRAME_PAGE_REFRESH";
export const FRAME_REGISTER_PAGECONTAINER = "FRAME_REGISTER_PAGECONTAINER";
export const FRAME_WINDOW_RESIZE = "FRAME_WINDOW_RESIZE";

export const FRAME_SCROLL_TO_TOP = "FRAME_SCROLL_TO_TOP";
export const FRAME_LOAD_USERAPPDATA = "FRAME_LOAD_USERAPPDATA";

export const PAGE_UPDATE_REFRESH = "PAGE_UPDATE_REFRESH";
export const PAGE_UPDATE_NOREFRESH = "PAGE_UPDATE_NOREFRESH";
export const PAGE_REFRESH = "PAGE_REFRESH";
export const PAGE_SET_STATE = "PAGE_SET_STATE";
export const PAGE_INIT_CUSTOM_REDUX = "PAGE_INIT_CUSTOM_REDUX";
export const PAGE_DSTY_CUSTOM_REDUX = "PAGE_DSTY_CUSTOM_REDUX";
export const PAGE_APPL_CUSTOM_REDUX = "PAGE_APPL_CUSTOM_REDUX";

export const FRAME_CHANGE_THEME = "FRAME_CHANGE_THEME";
export const PAGE_SET_CUR_MENU_DATA = "PAGE_SET_CUR_MENU_DATA";
export const PAGE_APPLY_REDUX = "PAGE_APPLY_REDUX";
export const FRAME_VALIDATE_USER = "FRAME_VALIDATE_USER";
