const TAPE_OPEN_RULEPANEL = 'TAPE_OPEN_RULEPANEL'
const TAPE_CLOSE_RULEPANEL = 'TAPE_OPEN_RULEPANEL'
const TAPE_EDIT_RULEPANEL = 'TAPE_EDIT_RULEDPANEL'
const TAPE_LASTSTEPPER = 'TAPE_LASTSTEPPER'
const TAPE_NEXTSTEPPER = 'TAPE_NEXTSTEPPER'
const TAPE_DISPATCH_RULEDATA = 'TAPE_DISPATCH_RULEDATA'
const TAPE_DISPATCH_ALERTDATA = 'TAPE_DISPATCH_ALERTDATA'
const TAPE_DELETE_RULEITEM = 'TAPE_DELETE_RULEITEM'
const TAPE_ADD_RULEITEM = 'TAPE_ADD_RULEITEM'
const TAPE_ADD_ALERTITEM = 'TAPE_ADD_ALERTITEM'
const TAPE_DELETE_ALERTITEM = 'TAPE_DELETE_ALERTITEM'
const TAPE_ADD_RULE_TASK = 'TAPE_ADD_RULE_TASK'
const TAPE_SELECT_APP = 'TAPE_SELECT_APP'
const TAPE_UPDATE_RULE_TASK = 'TAPE_UPDATE_RULE_TASK'
const TAPE_DELETE_RULE_TASK = 'TAPE_DELETE_RULE_TASK'
const TAPE_DEFDEL_RULE_TASK = 'TAPE_DEFDEL_RULE_TASK'
const TAPE_LOAD_APPDATA = 'TAPE_LOAD_APPDATA'
export {
  TAPE_OPEN_RULEPANEL, TAPE_CLOSE_RULEPANEL, TAPE_EDIT_RULEPANEL,
  TAPE_LASTSTEPPER, TAPE_NEXTSTEPPER, TAPE_DISPATCH_RULEDATA,
  TAPE_DISPATCH_ALERTDATA, TAPE_DELETE_RULEITEM, TAPE_ADD_RULEITEM,
  TAPE_DELETE_ALERTITEM, TAPE_ADD_ALERTITEM, TAPE_ADD_RULE_TASK,
  TAPE_SELECT_APP, TAPE_UPDATE_RULE_TASK, TAPE_DELETE_RULE_TASK,
  TAPE_DEFDEL_RULE_TASK,TAPE_LOAD_APPDATA
}