export const SNACKBAR_MESSAGE_PUSH = "SNACKBAR_MESSAGE_PUSH";
export const SNACKBAR_MESSAGE_CANCEL = "SNACKBAR_MESSAGE_CANCEL";
export const SNACKBAR_MESSAGE_SHOW = "SNACKBAR_MESSAGE_SHOW";
export const SNACKBAR_CLOSE = "SNACKBAR_CLOSE";
export const PAGECONTAINER_RESIZE = "PAGECONTAINER_RESIZE";
